analyzer:
  exclude:
    - build/**
    - android/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    directives_ordering: true
    use_key_in_widget_constructors: true
    close_sinks: true
